# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    depends_on:
      - redis
      - auth-service

  auth-service:
    build:
      context: ./backend/auth-service
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: